import React = require('react');
import COLORS from 'common/colors';
import common from 'common/common.styles';
import {Text} from 'react-native';
import responsivePixels from 'utils/responsivePixels';

const STRINGS_SPANISH = {
  rentNow: {
    btnRentNow: 'Alquile ahora',
    english: 'English',
    spanish: 'Spanish',
    condition: 'Términos y Condiciones',
    privacyPolicy: 'Política de Privacidad',
  },
  chooseLocation: {
    chooseLocationTxt: 'Elegir la ubicación',
  },

  insurancePlan: {
    screenHeader: 'Plan de seguro',
    insurancePlan: '¿Qué seguro quieres?',
    plansHeader: 'Lo que obtendrás',
    policyTerms1: 'Barcos, automóviles y remolques son ',
    policyTerms2: 'No cubierta ',
    policyTerms3:
      ' bajo seguro. Haga clic aquí para confirmar que comprende esto. ',
    insuranceValue: 'un mes',
    coverageValue: 'en cobertura',
    month: 'Mes',
    understood: 'Entendí',
    vehicaleBoats:
      'Los vehículos y embarcaciones no pueden estar cubiertos por el seguro. Revise los términos y condiciones de su contrato de seguro. Esta es una compañía de seguros externa y no está afiliada a Planet Storage LLC.',
  },

  storageSpaceSelection: {
    chooseYourSize: 'Elige tu talla',
    all: 'Toda',
    medium: 'Medio',
    large: 'grande',
    small: 'Pequeña',
    large1: 'Grande',
    howToUse: 'Cómo utilizar',
    howToUseDescription:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore.',
    understoodButtonTitle: 'Esta bien, entendí',
  },
  contactInfo: {
    screenHeader: 'Datos de contacto',
    yourContactInfo: 'Tu información de contacto',
    firstName: 'Nombre de pila',
    middleName: 'Segundo nombre',
    lastName: 'Apellido',
    contactNumber: 'Número de contacto',
    dateOfBirth: 'Fecha de nacimiento',

    address1: 'Address Line 1',
    address2: 'Address Line 2',
    country: 'Country',
    state: 'State',
    city: 'City',
    postalCode: 'Postal Code',
    typeDateOfBirth: 'Introduzca su fecha de nacimiento',
    typeAddress1: 'Introduzca su dirección 1',
    typeAddress2: 'Introduzca su dirección 2',
    typeCountry: 'Introduzca su País',
    typeState: 'Introduzca su estado',
    selectState: 'Seleccione su estado',
    searchState: 'Busque en su estado',
    typeCity: 'Introduzca su ciudad',
    typePostalCode: 'Introduzca su Código Postal',

    typeFirstName: 'Introduzca su nombre',
    typeMiddleName: 'Introduzca su segundo nombre',
    typeLastName: 'Introduzca tu apellido',
    typeContactNumber: 'Introduzca su número de contacto',
    typeLicenseNumber: 'Introduzca su número de licencia',
    typeBillingAddress: 'Introduzca Dirección de Envio',
    phoneNumber: 'Número de teléfono',
    typePhoneNumber: 'Introduzca su número de teléfono',
    alternatePhoneNumber: 'Número de teléfono alternativo',
    typeAlternatePhoneNumber: 'Introduzca su número de teléfono alternativo',
    emailAddress: 'Dirección de correo electrónico',
    typeEmailAddress: 'Introduzca su direccion de correo electronico',
    useAboveBilling:
      'Utilice la dirección anterior como dirección de facturación',
    billingAddress: 'Dirección de Envio',
    licenseNumber: 'Número de licencia',
  },
  secondContactInfo: {
    screenHeader: 'Segunda información de contacto',
    secondContactInfo:
      'Necesitamos un segundo punto de contacto en caso de que no podamos comunicarnos con usted.',
    secondContactName: 'Segundo nombre de contacto',
    firstName: 'Nombre de pila',
    middleName: 'Segundo nombre',
    lastName: 'Apellido',
    contactNumber: 'Número de contacto',
    typeFirstName: 'Introduzca su nombre',
    typeMiddleName: 'Introduzca su segundo nombre',
    typeLastName: 'Introduzca tu apellido',
    typeContactNumber: 'Introduzca su número de contacto',
    typeRelationship: 'Ingrese su relación',
    typeSecondContactName: 'Introduzca el nombre del segundo contacto',
    relationship: 'Relación',
    phoneNumber: 'Número de teléfono',
    typePhoneNumber: 'Introduzca su número de teléfono',
    emailAddress: 'Dirección de correo electrónico',
    typeEmailAddress: 'Introduzca su direccion de correo electronico',
  },
  contactDetails: {
    screenHeader: 'Detalles de contacto',
    contactDetails: '¿Todo parece correcto? Si NO, por favor haga cambios.',
    renterNameLabel: 'Nombre del inquilino',
    renterAddressLabel: 'Dirección del inquilino',
    renterPhoneLabel: 'Teléfono del inquilino',
    renterEmailLabel: 'Correo electrónico del inquilino',
    renterBillingAddressLabel: 'Dirección de facturación del inquilino',
    renterNameValue: 'Jacob Jones',
    renterAddressValue: '2715 Ash Dr. San Jose, South Dakota 83475',
    renterPhoneValue: '8085550111',
    renterEmailValue: 'tim.jennings@example.com',
    renterBillingAddressValue: '1901 Thornridge Cir. Shiloh, Hawaii 81063',

    secondContactNameLabel: 'Segundo nombre de contacto',
    secondContactPhoneLabel: 'Segundo número de contacto',
    secondContactEmailLabel: 'Correo electrónico de segundo contacto',
    secondContactInsuranceLabel: 'Seguro que deseas',
    sizeTypeInputLabel: 'Tamaño y tipo de unidad',
    secondContactNameValue: 'Annette Black',
    secondContactPhoneValue: '4055550128',
    secondContactEmailValue: 'willie.jennings@example.com',
    secondContactInsuranceValue: '$10,000 of coverages ($10.00 a month)',
    sizeTypeValue: '10’X40,',
    unit: 'Unidad',
    insurance: 'Seguro',
    size: 'Tamaño',
  },
  editRenterContactDetail: {
    editRenterContactDetailHeader:
      'Edite el campo siguiente con los detalles correctos',
    editRenterContactNameInputLabel: 'Nombre del inquilino',
    editRenterContactAddressInputLabel: 'Dirección del inquilino',
    editRenterContactPhoneInputLabel: 'Teléfono del inquilino',
    editRenterContactEmailInputLabel: 'Correo electrónico del inquilino',
    editRenterContactBillingAddressInputLabel:
      'Dirección de facturación del inquilino',

    editTypeRenterContactNameInputLabel: 'Introduzca su nombre',
    editTypeRenterContactAddressInputLabel: 'Introduzca su dirección',
    editTypeRenterContactPhoneInputLabel: 'Introduzca su número de teléfono',
    editTypeRenterContactEmailInputLabel:
      'Introduzca su direccion de correo electronico',
    editTypeRenterContactBillingAddressInputLabel:
      'Introduzca su dirección de facturación',
  },
  editSecondContactDetail: {
    editSecondContactDetailHeader:
      'Edite el campo siguiente con los detalles correctos',
    editSecondContactNameInputLabel: 'Segundo nombre de contacto',
    editSecondContactPhoneInputLabel: 'Segundo número de contacto',
    editSecondContactEmailInputLabel: 'Correo electrónico de segundo contacto',
    editSecondContactInsuranceInputLabel: 'Seguro que deseas',
    editSecondSizeTypeInputLabel: 'Tamaño y tipo de unidad',

    editTypeSecondContactNameInputLabel:
      'Introduzca el nombre del segundo contacto',
    editTypeSecondContactPhoneInputLabel: 'Introduzca su número de teléfono',
    editTypeSecondContactEmailInputLabel:
      'Introduzca su direccion de correo electronico',
    editTypeSecondContactInsuranceInputLabel: 'Tipo de seguro que desea',
    editTypeSecondSizeTypeInputLabel: 'Tamaño y tipo de unidad',
  },
  scanLicense: {
    scanLicense: 'Licencia de escaneo',
    screenHeader: 'Escanee su licencia de conducir con cámara',
    scanLicenseDefaultText: 'Su copia escaneada aparecerá aquí',
    cameraText: 'Toca para capturar',
  },
  scanCreditCards: {
    scanCreditCard: 'Escanear tarjeta de crédito',
    scanCreditCardHeader: 'Escanea tu tarjeta de crédito con cámara',
    scanCreditCardDefaultText: 'Su copia escaneada aparecerá aquí',
    scannerWarning:
      'Todo el pago del alquiler se cargará automáticamente a su tarjeta de crédito/débito cada mes.',
  },
  signAgreements: {
    signAgreement: 'firmar acuerdo',
    signInsuranceAgreement: 'Firmar acuerdo de seguro',
    signAgreementContent1:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore.\n \nLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    signAgreementCondition: 'Por favor acepta y ',
    // 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore.',
    signContractAgreement: 'Firmar contrato de alquiler',
    addSignature: 'Agregar firma',
  },
  summaryofCharge: {
    summaryofCharges: 'Resumen de cargos',
    unitDetails: 'Detalles de la unidad',
    rentalInformation: 'Información de alquiler',
    firstMonthRent: 'Alquiler del primer mes',
    firstRentProrated: 'Primer alquiler prorrateado',
    administrationFee: 'Cuota de administracion',
    taxes: 'Impuestos',
    total: 'Total',
    apply: 'Aplicar',
    reservationFee: 'Tarifa de reserva',
    protectionPlan: 'Plan de Protección - $2,000.00',
    applyPromoCode: 'Aplicar código promocional',
    unitVS: 'Unidad VS 107',
    unitValue: 'Unidad 10x40',
    $145: '$145/Mes',
    $43: '$43.50',
    $25: '$25.00',
    $145_0: '$145.00',
    date: '(10/05/23 - 31/05/23)',
    $82: '$82.10',
    $0: '$0.00',
    agreementDetails1: 'En el futuro se cargará su tarjeta ',
    agreementDetails2: 'Todos los pagos mensuales serán de pago automático.',
    // 'Consulte el contrato de arrendamiento para obtener más detalles.',
  },
  addCreditCard: {
    expityDatePlaceholder: 'Seleccionar fecha de vencimiento',
    screenHeader: 'Agregar tarjeta de crédito',
    addCardDetail: 'Agregue detalles para agregar su tarjeta',
    addCardNumberInputLabel: 'Ingrese el número de tarjeta',
    addCardInputPlaceholder: 'Por favor ingrese el nombre del titular de la tarjeta',
    addCardExipryInputLabel: 'Fecha de caducidad',
    addCardCVVInputLabel: 'Ingrese CVV',
    addCardCardHolderNameLabel: 'Nombre del titular de la tarjeta',
    alertMessage: 'Por favor confirme los datos de la tarjeta.',
  },
  payment: {
    paymentSuccessful: 'Pago exitosa',
    paymentSuccessfulContent:
      'Está lista para mudarse. Se le ha enviado un recibo por correo electrónico.',
    paymentUnitNumber: 'Su número de unidad',
    paymentUnitContent: 'Habrá un candado de cortesía en su unidad.',
    paymentGateCode: 'Su código de puerta',
    contactInfo: 'Información de contacto para preguntas',
    callOn: 'Recurrir',
    writeOn: 'Introduzca en',
    directionhowtoget: 'Instrucciones sobre cómo abrir su puerta',
    enterNumberUnit:
      'Ingrese el NÚMERO DE UNIDAD Seguido de # y CÓDIGO DE PUERTA Seguido de asterisco *',
    unitNumber: '305#1234*',
    gateCode: '1234',
    unitText: 'HAY UN CANDADO NUEVO EN EL PISO DE SU UNIDAD',
  },
  signUp: {
    header: 'Registration Form',
    firstName: 'First Name',
    lastName: 'Last Name',
    email: 'Email',
    password: 'Password',
    btnSignUp: 'SIGN UP',
  },
  login: {
    header: 'Login Form',
    email: 'Email',
    password: 'Password',
    forgotPassword: 'Forgot Password ?',
    btnSignIn: 'SIGN IN',
  },
  forgotPassword: {
    header: 'Forgot Password',
    email: 'Email',
  },
  changePassword: {
    header: 'Change Password',
    oldPassword: 'Old Password',
    newPassword: 'New Password',
    confirmPassword: 'Confirm Password',
    emptyOldPassword: 'Please enter old password',
    emptyNewPassword: 'Please enter new password',
    emptyConfirmPassword: 'Please enter confirm password',
    validOldPassword: 'Please enter valid old password',
    validNewPassword: 'Please enter valid new password',
    validConfirmPassword: 'Please enter valid confirm password',
  },
  validation: {
    emptyFirstName: 'Please enter first name',
    emptyLastName: 'Please enter last name',
    emptyEmail: 'Please enter email',
    emptyPassword: 'Please enter password ',
    validEmail: 'Please enter valid email',
    validPassword: 'Please enter valid password',
  },
  hello: 'Hello',

  english: 'English',
  hindi: 'हिंदी',
  spanish: 'Spanish',
  theme: 'Theme',

  textStrong: 'Fuerte',
  textMedium: 'Medio',
  textSoSo: 'Más o menos',
  textWeak: 'Débil',
  textVeryWeek: 'muy semana',
  textNoData: 'No hay registros disponibles',
  select: 'Seleccionar',
  btnReset: 'REINICIAR',

  btnSubmit: 'ENTREGAR',
  btnClear: 'Clara',
  btnUpdate: 'Actualizar',
  btnNext: 'Próxima',
  btnReload: 'Intentar otra vez', //'Try Again', //'Recargar',
  btnAddNow: 'Añadir ahora',
  btnClose: 'Cerca',
  btnSubmit1: 'Entregar',
  btnPayNow: 'Pagar ahora',
  btnFinishClickHere: 'Terminar Haga clic aquí',
  btnBack: 'Atrás',
  btnOk: 'De acuerdo',
  btnAddManually: 'Agregar manualmente',
  emptyFieldError: `Archivado no puede estar vacío`,
  validateErrorMessage: 'Por favor introduce un dato válido',

  validErrorMessage: 'Por favor ingrese una valida ',
  dateOfBirthError: 'Por favor seleccione fecha de nacimiento',
  emptyError: 'Por favor ingrese una ',
  requiredError: ' se requiere.',
  contactNumberError: 'Por favor ingrese un número de 10 dígitos',
  emailError: `Ingrese la dirección de correo electrónico con el formato: 'nombre de usuario@dominio.com'`,
  nameError: 'Utilice sólo caracteres alfabéticos',

  licenseError: 'Escanee su licencia',
  licenseScanSuccess: 'Documento capturado exitosamente',

  errorNetwork: 'Please try after sometimes as there is some technical issues.',
  errorNoNetwork: 'Sin conexión a Internet',
  // 'No internet connection available. Please check your connection and try again.',
  errorNetworkTimeOut: 'Login timed out. Please try again after some time.',
  copyrightFooter: ' Aspen Mini Storage | All rights reserved', //' Mini almacenamiento Aspen | Reservados todos los derechos',
  month: 'Mes',
  Button_Confirm: 'Confirmar',
  Button_Cancel: 'Cancelar',
};

export default STRINGS_SPANISH;
